Fix benchmark
travisstaloch/art.zig pull request #13
Opened 2023-09-24 07:54 UTC by iacore

.....

```

StringHashMap
insert 22ms, search 9ms, delete 9ms, combined 40ms

Art
insert 28ms, search 19ms, delete 22ms, combined 69ms
```

2023-09-26 07:35 UTC, travisstaloch requested changes

2023-09-26 07:35 UTC, travisstaloch commented on src/bench2.zig
>              const line_ = try _container.allocator.dupeZ(u8, line);
This dupeZ() isn't needed any more. Would you mind removing it?

2023-09-26 07:37 UTC, travisstaloch commented on src/bench2.zig
>              const line_ = try _container.allocator.dupeZ(u8, line);
Oops wrong line. Meant for line 24.

2023-09-26 07:43 UTC, travisstaloch commented
Actually I think it might be an easier job to just change `fileEachLine()` to accept the lines. Then perhaps move the code which allocates the lines into a helper so that it can be used in the tests.

2023-09-26 07:51 UTC, travisstaloch requested changes

2023-09-26 07:51 UTC, travisstaloch commented on src/bench2.zig
> +        while (try reader.readUntilDelimiterOrEofAlloc(a, '\n', 512)) |line| {
Lets get rid the allocation when reading the file:

```zig
        const reader = f.reader();
        var buf: [512]u8 = undefined;
        while (try reader.readUntilDelimiterOrEof(&buf, '\n')) |line|
```

2023-09-26 22:31 UTC, iacore commented
> So I guess that this PR shows the previous benchmark was flawed and spending so much time reading lines from the file that the timings became pointless. Would you say this is correct?

yes

2023-09-27 12:22 UTC, travisstaloch commented
Thanks for the patch. :+1:  I'm going to accept this now.  I'll follow with a patch to implement the other changes I requestd.

2023-09-27 12:22 UTC, travisstaloch approved these changes

2023-09-27 12:22 UTC, merged